apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - namespace.yaml
  - ../../base
  - dragonfly.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: course-app
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: course-app