apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: lesson-13-hw
  url: ssh://git@github.com/MHavshyn/rd-fluxcd-lesson
  secretRef:
    name: flux-system
