apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config
  labels:
    app: course-app
data:
  APP_MESSAGE: "Hello from Flux GitOps"
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://dragonfly:6379/0"